# config/meta.yml

meta_product_name: "Canaduh"
meta_title: "Welcome to Canaduh, your immigration helper!"
meta_description: "Looking for help with your diiferent applications to Canada?
Set an appointment with our list of egulated, professional immigration consultants
and get the assistance you need through your path."
meta_image: "logo.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
